# Generated by Django 6.0.7 on 2026-08-05 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.TextField(default='')),
                ('product_type', models.CharField(choices=[('E', 'ELECTRONIC'), ('C', 'CLOTHES'), ('H', 'HOUSEHOLD')], max_length=1)),
            ],
        ),
    ]
